### ISSUE TITLE
angenommen Funkspruch temp. fixieren

### ISSUE THREAD

**Issue by TigaPlays** [TheKeineAhnung/resi-script-manager#17]
Ein angenommen Sprechwunsch (Lagemeldung, Nachforderung) vorübergehend fixieren.

+ nach Annahme automatisch
dann
- zum manuell Lösen
oder
- für paar Sekunden (z.b. 6 sec. oder einstellbar)

**Comment by Notme112** [comment]
Könnte man auch in der Codebase umsetzten

**Comment by TheKeineAhnung** [comment]
Kannst du gerne haben @Notme112. Hab ich keine Lust drauf

**Comment by Notme112** [comment]
Nehmen wir. @TigaPlays bitte nochmal auf dem Discord, sonst geht das unter
