### ISSUE TITLE
Verbands-Menü verbessern

### ISSUE THREAD

**Issue by TigaPlays** [TheKeineAhnung/resi-script-manager#20]
Ergänzen der Links von
- Verbandsgebäude
- Verbands-Protokoll (für Co-/Admin)

![image](https://user-images.githubusercontent.com/97369124/163472878-4545e491-f3ca-4532-9204-40ab83f1d351.png)

**Comment by Notme112** [comment]
Ich weiß nicht, ob ich dir das mal geschrieben habe, aber, da das Tooltip mit einem Framework erzeugt wird, ist es für uns ziemlich schwierig, da drin rumzupfuschen. Ich fände das sonst auch nativ ganz gut.

**Comment by TheKeineAhnung** [comment]
Zu schlechter Zeit/nutzen aufwand. Wird von mir nicht gemacht
