### ISSUE TITLE
Import der Einstellungen 

### ISSUE THREAD

**Issue by TigaPlays** [TheKeineAhnung/resi-script-manager#22]
**Describe the bug**
Import der Einstellungen
Wenn man weis wie, funktioniert es.
Mein Modul zum reproduzieren war "Patientenanzahl"

**To Reproduce**
1. Ein Modul deaktivieren ->  Speichern & neuladen
2. Einstellungen importieren -> Speichern -> es kommt die Meldung "Einstellungen gespeichert"
3. zurück auf Module, dass Modul ist nicht wieder aktiv -> **Speichern & neuladen bleibt ohne Funktion**
ich habe nochmals Schritt 2 ,den Import, durchgeführt und dann
4. mit x Resi-Script-Manager geschlossen und dann erneut geöffnet
5. nun wird das Modul als aktiv angezeigt
6. Speichern & neuladen
7. jetzt funktioniert das Modul wieder

**Expected behavior**
Nach Schritt 2 wieder die Seite neugeladen

**Screenshots**

**Please complete the following information:**
 - OS: Windows 10 Pro
 - Version: 21H1
 - Browser: Google Chrome
 - Browser version: Chrome ist auf dem neuesten Stand
Version 100.0.4896.127 (Offizieller Build) (64-Bit)

**Additional context**
Wenn man weis wie, funktioniert es. :P

**Comment by TheKeineAhnung** [comment]
Das nicht neugeladen wird stimmt schon und auch, dass die Module nicht geladen werden ohne reload. Der Fehler liegt eher darin, dass der Switch nicht automatisch aktualisiert wird.
