### ISSUE TITLE
Tập lệnh không còn hoạt động

### ISSUE THREAD

**Issue by Locke12801** [TheKeineAhnung/resi-script-manager#32]
**Describe the bug**

**To Reproduce**

1.
2. 
3. 

**Expected behavior**

**Screenshots**

**Please complete the following information:**
 - Version: [e.g. 1.0.0]
 - Browser: 
 - Browser version: [e.g. 93.1]

**Additional context**

**Comment by TheKeineAhnung** [comment]
Closed due to lack of information
