### ISSUE TITLE
Anzeige Uhrzeit unschön

### ISSUE THREAD

**Issue by QuCla** [TheKeineAhnung/resi-script-manager#44]
Die Uhrzeit wird unschön angezeigt, damit meine ich: 18:9:10 anstatt 18:09:10

Benutze als Browser Firefox.

**Comment by TheKeineAhnung** [comment]
Bitte führe den Fehler etwas weiter aus. Es ist kein Skript, welches die Uhrzeit nutzt vorhanden. Halte dich bitte an die [Vorlage](https://github.com/TheKeineAhnung/resi-script-manager/blob/dev/.github/ISSUE_TEMPLATE/bug_report.md) um Fehler zu melden.
